import mongoose from 'mongoose';

const aiToolGenerationSchema = new mongoose.Schema(
  {
    toolName: { type: String, required: true, index: true },
    toolDisplayName: { type: String, default: '' },
    /** Single source of truth: how this row was created */
    sourceType: {
      type: String,
      enum: ['ai_generator', 'ai_pdf', 'book_rag', 'legacy'],
      default: 'legacy',
      index: true,
    },
    board: { type: String, default: '', index: true },
    /** IIT product track (ALPHA / BETA / …). Empty = General. */
    productCategory: {
      type: String,
      default: '',
      trim: true,
      uppercase: true,
      index: true,
    },
    classLabel: { type: String, required: true, index: true },
    subject: { type: String, required: true, index: true },
    topic: { type: String, default: '' },
    subtopic: { type: String, default: '' },
    section: { type: String, default: '', index: true },
    content: { type: String, default: '' },
    generatedContent: { type: String, default: '' },
    pdfFileUrl: { type: String, default: '' },
    pdfFileName: { type: String, default: '' },
    /** User id (ObjectId) or legacy string id (e.g. super-admin) */
    generatedBy: { type: mongoose.Schema.Types.Mixed, default: null, index: true },
    status: { type: String, default: 'active', index: true },
    /**
     * Governance workflow for AI-generated content (Phase 2.4).
     * - 'approved'      : visible to teachers/students. Default for backwards-compat with pre-existing rows.
     * - 'draft'         : freshly generated by Super Admin/AI Generator, NOT visible to teachers/students yet.
     * - 'under_review'  : flagged for human review.
     * - 'rejected'      : reviewer rejected, do not surface.
     * - 'archived'      : superseded by a newer approved version.
     */
    reviewStatus: {
      type: String,
      enum: ['approved', 'draft', 'under_review', 'rejected', 'archived'],
      default: 'approved',
      index: true,
    },
    reviewedBy: { type: mongoose.Schema.Types.Mixed, default: null },
    reviewedAt: { type: Date, default: null },
    reviewerNotes: { type: String, default: '' },
    teacherId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    metadata: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { timestamps: true },
);

aiToolGenerationSchema.index({
  board: 1,
  productCategory: 1,
  toolName: 1,
  classLabel: 1,
  subject: 1,
  topic: 1,
  subtopic: 1,
});
aiToolGenerationSchema.index({
  productCategory: 1,
  classLabel: 1,
  subject: 1,
  topic: 1,
  subtopic: 1,
  createdAt: -1,
});
aiToolGenerationSchema.index({
  board: 1,
  toolName: 1,
  classLabel: 1,
  subject: 1,
  topic: 1,
  subtopic: 1,
});
aiToolGenerationSchema.index({
  classLabel: 1,
  subject: 1,
  topic: 1,
  subtopic: 1,
  createdAt: -1,
});
aiToolGenerationSchema.index({ sourceType: 1, toolName: 1, createdAt: -1 });
aiToolGenerationSchema.index({ 'metadata.contentEngineSourceId': 1 });
aiToolGenerationSchema.index({ reviewStatus: 1, updatedAt: -1 });
aiToolGenerationSchema.index({ reviewStatus: 1, classLabel: 1, subject: 1, createdAt: -1 });
aiToolGenerationSchema.index({ 'metadata.bookGenerator': 1, createdAt: -1 });
aiToolGenerationSchema.index({ sourceType: 1, board: 1, createdAt: -1 });

function bumpHierarchyCache() {
  try {
    // Lazy import avoids circular init with controllers that import this model.
    import('../utils/ai-tool-hierarchy-cache.js')
      .then((m) => m.clearAiToolHierarchyCache?.())
      .catch(() => {});
  } catch {
    // ignore
  }
}

aiToolGenerationSchema.post('save', bumpHierarchyCache);
aiToolGenerationSchema.post('insertMany', bumpHierarchyCache);
aiToolGenerationSchema.post('findOneAndUpdate', bumpHierarchyCache);
aiToolGenerationSchema.post('findOneAndDelete', bumpHierarchyCache);
aiToolGenerationSchema.post('deleteOne', bumpHierarchyCache);
aiToolGenerationSchema.post('deleteMany', bumpHierarchyCache);

const AiToolGeneration =
  mongoose.models.AiToolGeneration ||
  mongoose.model('AiToolGeneration', aiToolGenerationSchema);

export default AiToolGeneration;
